#cloud-config
ssh_pwauth: true
disable_root: false

chpasswd:
  list: |
    root:ubuntu
  expire: false

packages:
  - curl
  - wget
  - python3
  - python3-pip

runcmd:
  - sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
  - sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
  - systemctl restart ssh
