#cloud-config
locale: en_US.UTF-8
timezone: Asia/Tokyo

# パスワード認証を有効化
ssh_pwauth: true
disable_root: false

# ユーザー設定
users:
  - default
  - name: ubuntu
    passwd: $6$salt$3yTvKQVn7nDw1yVFyBa6V8kVjEQQQNQQ5KjEQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ
    lock_passwd: false
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
  - name: admin
    passwd: $6$salt$3yTvKQVn7nDw1yVFyBa6V8kVjEQQQNQQ5KjEQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ
    lock_passwd: false
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']

# パッケージインストール
packages:
  - curl
  - wget
  - git
  - python3
  - python3-pip
  - net-tools
  - tcpdump
  - openssh-server

package_update: true
package_upgrade: true

# SSH設定の調整
write_files:
  - path: /etc/ssh/sshd_config.d/99-custom.conf
    content: |
      PasswordAuthentication yes
      PermitRootLogin yes
      PubkeyAuthentication yes
    permissions: '0644'

runcmd:
  - systemctl enable ssh
  - systemctl restart ssh
  - echo "ubuntu:ubuntu" | chpasswd
  - echo "admin:ubuntu" | chpasswd
  - echo "root:ubuntu" | chpasswd
  - echo "Base setup completed" > /var/log/cloud-init-setup.log

final_message: "System ready - Login: ubuntu/ubuntu or admin/ubuntu"